#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

using std::string;

int main(int argc, char *argv[]) {
    // check check check
    if (argc < 2) {
        std::cerr << "No project name provided.\n";
        return 1;
    }
    string arg1 = argv[1];

    if (arg1 == "--help" || arg1 == "-h") {
        std::cout << "koiinit - tiny C++ project initializer\n\n";
        std::cout << "Usage:\n";
        std::cout << "  koiinit <project-name>\n";
        std::cout << "  koiinit <project-name> --cmake\n";
        std::cout << "  koiinit <project-name> --git\n";
        std::cout << "  koiinit <project-name> --cmake --git\n";
        std::cout << "  koiinit --help\n\n";
        std::cout << "Options:\n";
        std::cout << "  --cmake   Generate a CMake project instead of Meson\n";
        std::cout << "  --help    Show this help message\n";
        std::cout << "  --git     Initialize a Git repository\n";
        return 0;
    }
    bool use_cmake = false;
    bool use_git = false;
    for (int i = 2; i < argc; i++) {
        string arg = argv[i];

        if (arg == "--cmake") {
            use_cmake = true;
        } else if (arg == "--git") {
            use_git = true;
        } else {
            std::cerr << "Unknown option: " << arg << '\n';
            return 1;
        }
    }
    string projectname = argv[1];

    if (projectname == "test") {
        std::cerr << "'test' is reserved by Meson.\n";
        return 1;
    }
    // I take it back, filesystem is nice library for c++ :)
    // make the main file and variables.
    std::filesystem::create_directory(projectname);
    string srcdir = projectname + "/src/";
    std::filesystem::create_directory(srcdir);
    std::ofstream mainfile(projectname + "/src/main.cpp");
    if (mainfile.is_open()) {
        mainfile << "#include <iostream>\n\n";
        mainfile << "int main() {\n";
        mainfile << "    std::cout << \"Hello, World!\\n\";\n";
        mainfile << "    return 0;\n";
        mainfile << "}\n";
    }
    // I dont rlly like cmake but I'll add it bc it would be convenient^^
    if (use_cmake) {
        std::ofstream cmakefile(projectname + "/CMakeLists.txt");

        if (cmakefile.is_open()) {
            cmakefile << "cmake_minimum_required(VERSION 3.16)\n";
            cmakefile << "project(" << projectname << " LANGUAGES CXX)\n\n";
            cmakefile << "set(CMAKE_CXX_STANDARD 20)\n";
            cmakefile << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n";
            cmakefile << "add_executable(" << projectname << " src/main.cpp)\n";
        }
    } else {
        // I prob should make a helper to make these
        std::ofstream mesonfile(projectname + "/meson.build");

        if (mesonfile.is_open()) {
            mesonfile << "project('" << projectname << "', 'cpp')\n\n";
            mesonfile << "executable('" << projectname
                      << "', 'src/main.cpp', install: true)\n";
        }
    }
    std::ofstream readmefile(projectname + "/README.md");
    if (readmefile.is_open()) {
        readmefile << "# " << projectname << "\n\n";
        readmefile << "<!--\n";
        readmefile << "This readme was autogenerated by koi.\n";
        readmefile << "Please edit it freely before uploading.\n";
        readmefile << "-->\n";
        // I decided to add the autogenerated message cuz why not?
    }
    // create the gitignore
    std::ofstream gitignore(projectname + "/.gitignore");
    if (gitignore.is_open()) {
        gitignore << "build/\n";
        gitignore << ".cache/\n";
    }
    // initialize a empty git repo if --git is specified.
    if (use_git) {
        string command = "git init -b main \"" + projectname + "\"";
        std::system(command.c_str());
    }
    // We check to see if its using cmake or meson to change the final print.
    if (use_cmake) {
        std::cout << "Created project '" << projectname << "' using CMake.\n";
    } else {
        std::cout << "Created project '" << projectname << "' using Meson.\n";
    }
}
